### ISSUE TITLE
Suggestion: Add expected inflation rate for current year

### ISSUE THREAD

**Issue by ackvf** [martin-majlis/inflacni-kalkulacka.cz#7]
Mohl bys prosím přidat políčko pro zadání předpokládané meziroční inflace podobně jako to má tato kalkulačka? https://www.penize.cz/kalkulacky/znehodnoceni-koruny-inflace#inflace-vypocet
Ta jejich je však naprd, neumí vzít v potaz skutečnou minulou inflaci, když se snažím vypočítat budoucí inflaci na 2023.

**Comment by martin-majlis** [comment]
Ahoj, moc jsem sem nekoukal. Vyresil jsem to v #10 tim, ze jsem pridal predicki CNB.
